name: daily-report

on:
  schedule:
    - cron: '30 10-22 * * 1-6'  # Este cron ejecuta el flujo de trabajo cada hora entre las 10:30 y las 22:30, de lunes a sábado (días 1 al 6)
  workflow_dispatch:    # This allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Specify the desired Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run QuiniNow code
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}  # Assuming you have a secret named "WEBHOOK_URL"
        run: python Main.py  # Replace with the correct script name
